Added in support for custom columns
google/swift-benchmark pull request #32
Opened 2020-05-20 06:52 UTC by McJones

This is a preliminary attempt at adding in user selectable columns to resolve #15.

Currently only the name column is assumed and also the leading column.
This does mean you could say request the standard deviation and nothing else which makes little sense.
Unsure as to exactly what combinations of columns should be allowed, or if allowing anything is ok.

2020-05-20 06:53 UTC, McJones commented
@googlebot I signed it!

2020-05-20 18:00 UTC, saeta requested changes
Thank you very much @McJones for this PR! I suspect @shabalind will have some additional thoughts shortly, but I wanted to send this along as I had it.

2020-05-20 18:00 UTC, saeta commented on Sources/Benchmark/BenchmarkCommand.swift
> +public enum Column: String, ExpressibleByArgument, Decodable {
I think we'll want to allow custom metrics (https://github.com/google/swift-benchmark/issues/11) that are defined on a per-benchmark basis. As a result, I think having an enum is not the right design here, as an enum induces a 'closed set' vs a desired 'open set'. Does that make sense?

2020-05-20 18:00 UTC, saeta commented on Sources/Benchmark/BenchmarkCommand.swift
> +    @Option(name: .customLong("show"), parsing: .upToNextOption, help: "Desired columns to be included in the output")
Could you add a quick unit test to ensure this parses correctly?

2020-05-20 18:00 UTC, saeta commented on Sources/Benchmark/BenchmarkReporter.swift
> +    var columns: [Column] { get set }
Are you sure this is necessary here? I think you might be able to simplify a bit if this isn't required.

2020-05-25 17:00 UTC, shabalind requested changes
The implementation here needs to be updated due to recent changes on master.

2020-06-12 17:10 UTC, shabalind commented
Hi @McJones thanks a lot for contribution, but this PR is now superseded by #42.

2020-06-12 17:10 UTC, closed without merging