Add optional setUp and tearDown requirements to AnyBenchmark
google/swift-benchmark pull request #33
Opened 2020-05-23 18:30 UTC by mattt

This is an alternative solution to what was discussed in #29. Rather than introducing a new pattern for defining setup and teardown behavior, this PR implements this functionality using the same, familiar pattern seen in [`XCTest`](https://developer.apple.com/documentation/xctest/xctestcase).

By providing a default implementation of `setUp()` and `tearDown()` in an unconstrained extension on the `AnyBenchmark` protocol, we make them effectively optional requirements. This change has no impact on existing code.

2020-05-23 18:32 UTC, mattt commented
If either `setUp` or `tearDown` are expensive operations, intermediary results can be memoized in a lazy variable or some other cache mechanism using standard Swift language features.

2020-05-25 11:59 UTC, mattt commented
As I [mentioned in #29](https://github.com/google/swift-benchmark/issues/29#issuecomment-633536235):

> You could add `setUp` and `tearDown` closure arguments to the `benchmark` function (defaulting to `nil` so that they don't have to be specified):
 
```swift
benchmark("...", setUp: { /* ... */ }, tearDown: { /* ... */ }) { 
   /* ... */
}
```

> Or, if you wanted to target the forthcoming multiple trailing closures proposal in [SE-0279](https://github.com/apple/swift-evolution/blob/master/proposals/0279-multiple-trailing-closures.md), you'd implement a separate overload of `benchmark` that requires all three closure arguments in a different order:

```swift
benchmark("...") {
  /* ... */
} setUp: {
  /* ... */
} tearDown: {
  /* ... */
}
```

Let me know if you'd like me to  add either of those to this PR.

2020-05-25 12:22 UTC, shabalind requested changes
Hi @mattt, as explained in https://github.com/google/swift-benchmark/issues/29#issuecomment-633542558 and https://github.com/google/swift-benchmark/issues/29#issuecomment-633544284 I suggest we don't add multiple closure overloads. 

The underlying change on this PR looks good to me, the only comment is please add a test to make sure that `setUp` and `tearDown` are called by the framework.

2020-05-25 14:03 UTC, shabalind approved these changes
LGTM, thanks @mattt! 👍

2020-05-25 14:03 UTC, merged

2020-05-25 14:06 UTC, mattt commented
Thanks, @shabalind!