Make `BenchmarkRunner` publicly accessible
google/swift-benchmark pull request #63
Opened 2020-07-16 19:49 UTC by texasmichelle

Makes `BenchmarkRunner` publicly accessible, for short-circuiting `BenchmarkMain` and accessing result measurements directly. This is useful for sending individual results to other systems, rather than just printing a summary.

2020-07-16 20:06 UTC, shabalind requested changes

2020-07-16 20:06 UTC, shabalind commented on Sources/Benchmark/BenchmarkRunner.swift
> +    public var results: [BenchmarkResult] = []
Needs a doc comment.

2020-07-16 20:06 UTC, shabalind commented on Sources/Benchmark/BenchmarkRunner.swift
> +    public mutating func run() throws {
This one as well.

2020-07-17 15:27 UTC, texasmichelle commented on Sources/Benchmark/BenchmarkRunner.swift
> +    public var results: [BenchmarkResult] = []
Done.

2020-07-17 15:27 UTC, texasmichelle commented on Sources/Benchmark/BenchmarkRunner.swift
> +    public mutating func run() throws {
Done.

2020-07-17 16:01 UTC, shabalind approved these changes
LGTM! 👍

2020-07-17 16:02 UTC, merged